package com.hand.base.smscode.dao.mybatis.mapper;


import java.util.List;

import com.hand.base.smscode.model.MessageTemplate;

public interface MessageTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CX_O_MSG_TEMP
     *
     * @mbggenerated
     */
    int insert(MessageTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CX_O_MSG_TEMP
     *
     * @mbggenerated
     */
    int insertSelective(MessageTemplate record);
    
    List<MessageTemplate> getByType(String type);
}