package com.hand.base.smscode.dao.mybatis.mapper;

import java.util.List;
import java.util.Map;

import com.hand.base.smscode.model.SmsLog;

public interface SmsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CX_O_SMS_LOG
     *
     * @mbggenerated
     */
    int insert(SmsLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CX_O_SMS_LOG
     *
     * @mbggenerated
     */
    int insertSelective(SmsLog record);
    
    List<SmsLog> selectCode(SmsLog record);
    
    List<SmsLog> select(Map<String, Object> hs);
    
    int updateByPrimaryKeySelective(SmsLog record);
    
    int deleteByPrimaryKey(String rowId);
}