package com.hand.base.smscode.dao.mybatis.mapper;


import com.hand.base.smscode.model.SystemConfig;

public interface SystemConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CX_O_SYSTEM
     *
     * @mbggenerated
     */
    int insert(SystemConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CX_O_SYSTEM
     *
     * @mbggenerated
     */
    int insertSelective(SystemConfig record);
    
    String getByName(String name);
    
    String getByCode(String name);
    
    String getSMSPlatformByCode(String name);
}