package com.hand.base.smscode.model;


import java.math.BigDecimal;
import java.util.Date;

public class MessageTemplate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CX_O_MSG_TEMP.ROW_ID
     *
     * @mbggenerated
     */
    private String rowId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CX_O_MSG_TEMP.CREATED
     *
     * @mbggenerated
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CX_O_MSG_TEMP.CREATED_BY
     *
     * @mbggenerated
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CX_O_MSG_TEMP.LAST_UPD
     *
     * @mbggenerated
     */
    private Date lastUpd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CX_O_MSG_TEMP.LAST_UPD_BY
     *
     * @mbggenerated
     */
    private String lastUpdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CX_O_MSG_TEMP.MODIFICATION_NUM
     *
     * @mbggenerated
     */
    private Long modificationNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CX_O_MSG_TEMP.CONFLICT_ID
     *
     * @mbggenerated
     */
    private String conflictId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CX_O_MSG_TEMP.DB_LAST_UPD
     *
     * @mbggenerated
     */
    private Date dbLastUpd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CX_O_MSG_TEMP.T_ATTR_09
     *
     * @mbggenerated
     */
    private BigDecimal tAttr09;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CX_O_MSG_TEMP.T_ATTR_10
     *
     * @mbggenerated
     */
    private BigDecimal tAttr10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CX_O_MSG_TEMP.T_ATTR_11
     *
     * @mbggenerated
     */
    private BigDecimal tAttr11;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CX_O_MSG_TEMP.T_ATTR_12
     *
     * @mbggenerated
     */
    private Date tAttr12;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CX_O_MSG_TEMP.T_ATTR_13
     *
     * @mbggenerated
     */
    private Date tAttr13;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CX_O_MSG_TEMP.T_ATTR_14
     *
     * @mbggenerated
     */
    private Date tAttr14;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CX_O_MSG_TEMP.DB_LAST_UPD_SRC
     *
     * @mbggenerated
     */
    private String dbLastUpdSrc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CX_O_MSG_TEMP.MSG_CONTEXT
     *
     * @mbggenerated
     */
    private String msgContext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CX_O_MSG_TEMP.T_ATTR_01
     *
     * @mbggenerated
     */
    private String msgType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CX_O_MSG_TEMP.T_ATTR_02
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CX_O_MSG_TEMP.T_ATTR_03
     *
     * @mbggenerated
     */
    private String tAttr03;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CX_O_MSG_TEMP.T_ATTR_04
     *
     * @mbggenerated
     */
    private String tAttr04;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CX_O_MSG_TEMP.T_ATTR_05
     *
     * @mbggenerated
     */
    private String tAttr05;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CX_O_MSG_TEMP.T_ATTR_06
     *
     * @mbggenerated
     */
    private String tAttr06;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CX_O_MSG_TEMP.T_ATTR_07
     *
     * @mbggenerated
     */
    private String tAttr07;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CX_O_MSG_TEMP.T_ATTR_08
     *
     * @mbggenerated
     */
    private String tAttr08;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CX_O_MSG_TEMP.T_ATTR_15
     *
     * @mbggenerated
     */
    private String tAttr15;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CX_O_MSG_TEMP.ROW_ID
     *
     * @return the value of CX_O_MSG_TEMP.ROW_ID
     *
     * @mbggenerated
     */
    public String getRowId() {
        return rowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CX_O_MSG_TEMP.ROW_ID
     *
     * @param rowId the value for CX_O_MSG_TEMP.ROW_ID
     *
     * @mbggenerated
     */
    public void setRowId(String rowId) {
        this.rowId = rowId == null ? null : rowId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CX_O_MSG_TEMP.CREATED
     *
     * @return the value of CX_O_MSG_TEMP.CREATED
     *
     * @mbggenerated
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CX_O_MSG_TEMP.CREATED
     *
     * @param created the value for CX_O_MSG_TEMP.CREATED
     *
     * @mbggenerated
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CX_O_MSG_TEMP.CREATED_BY
     *
     * @return the value of CX_O_MSG_TEMP.CREATED_BY
     *
     * @mbggenerated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CX_O_MSG_TEMP.CREATED_BY
     *
     * @param createdBy the value for CX_O_MSG_TEMP.CREATED_BY
     *
     * @mbggenerated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CX_O_MSG_TEMP.LAST_UPD
     *
     * @return the value of CX_O_MSG_TEMP.LAST_UPD
     *
     * @mbggenerated
     */
    public Date getLastUpd() {
        return lastUpd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CX_O_MSG_TEMP.LAST_UPD
     *
     * @param lastUpd the value for CX_O_MSG_TEMP.LAST_UPD
     *
     * @mbggenerated
     */
    public void setLastUpd(Date lastUpd) {
        this.lastUpd = lastUpd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CX_O_MSG_TEMP.LAST_UPD_BY
     *
     * @return the value of CX_O_MSG_TEMP.LAST_UPD_BY
     *
     * @mbggenerated
     */
    public String getLastUpdBy() {
        return lastUpdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CX_O_MSG_TEMP.LAST_UPD_BY
     *
     * @param lastUpdBy the value for CX_O_MSG_TEMP.LAST_UPD_BY
     *
     * @mbggenerated
     */
    public void setLastUpdBy(String lastUpdBy) {
        this.lastUpdBy = lastUpdBy == null ? null : lastUpdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CX_O_MSG_TEMP.MODIFICATION_NUM
     *
     * @return the value of CX_O_MSG_TEMP.MODIFICATION_NUM
     *
     * @mbggenerated
     */
    public Long getModificationNum() {
        return modificationNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CX_O_MSG_TEMP.MODIFICATION_NUM
     *
     * @param modificationNum the value for CX_O_MSG_TEMP.MODIFICATION_NUM
     *
     * @mbggenerated
     */
    public void setModificationNum(Long modificationNum) {
        this.modificationNum = modificationNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CX_O_MSG_TEMP.CONFLICT_ID
     *
     * @return the value of CX_O_MSG_TEMP.CONFLICT_ID
     *
     * @mbggenerated
     */
    public String getConflictId() {
        return conflictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CX_O_MSG_TEMP.CONFLICT_ID
     *
     * @param conflictId the value for CX_O_MSG_TEMP.CONFLICT_ID
     *
     * @mbggenerated
     */
    public void setConflictId(String conflictId) {
        this.conflictId = conflictId == null ? null : conflictId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CX_O_MSG_TEMP.DB_LAST_UPD
     *
     * @return the value of CX_O_MSG_TEMP.DB_LAST_UPD
     *
     * @mbggenerated
     */
    public Date getDbLastUpd() {
        return dbLastUpd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CX_O_MSG_TEMP.DB_LAST_UPD
     *
     * @param dbLastUpd the value for CX_O_MSG_TEMP.DB_LAST_UPD
     *
     * @mbggenerated
     */
    public void setDbLastUpd(Date dbLastUpd) {
        this.dbLastUpd = dbLastUpd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CX_O_MSG_TEMP.T_ATTR_09
     *
     * @return the value of CX_O_MSG_TEMP.T_ATTR_09
     *
     * @mbggenerated
     */
    public BigDecimal gettAttr09() {
        return tAttr09;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CX_O_MSG_TEMP.T_ATTR_09
     *
     * @param tAttr09 the value for CX_O_MSG_TEMP.T_ATTR_09
     *
     * @mbggenerated
     */
    public void settAttr09(BigDecimal tAttr09) {
        this.tAttr09 = tAttr09;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CX_O_MSG_TEMP.T_ATTR_10
     *
     * @return the value of CX_O_MSG_TEMP.T_ATTR_10
     *
     * @mbggenerated
     */
    public BigDecimal gettAttr10() {
        return tAttr10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CX_O_MSG_TEMP.T_ATTR_10
     *
     * @param tAttr10 the value for CX_O_MSG_TEMP.T_ATTR_10
     *
     * @mbggenerated
     */
    public void settAttr10(BigDecimal tAttr10) {
        this.tAttr10 = tAttr10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CX_O_MSG_TEMP.T_ATTR_11
     *
     * @return the value of CX_O_MSG_TEMP.T_ATTR_11
     *
     * @mbggenerated
     */
    public BigDecimal gettAttr11() {
        return tAttr11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CX_O_MSG_TEMP.T_ATTR_11
     *
     * @param tAttr11 the value for CX_O_MSG_TEMP.T_ATTR_11
     *
     * @mbggenerated
     */
    public void settAttr11(BigDecimal tAttr11) {
        this.tAttr11 = tAttr11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CX_O_MSG_TEMP.T_ATTR_12
     *
     * @return the value of CX_O_MSG_TEMP.T_ATTR_12
     *
     * @mbggenerated
     */
    public Date gettAttr12() {
        return tAttr12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CX_O_MSG_TEMP.T_ATTR_12
     *
     * @param tAttr12 the value for CX_O_MSG_TEMP.T_ATTR_12
     *
     * @mbggenerated
     */
    public void settAttr12(Date tAttr12) {
        this.tAttr12 = tAttr12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CX_O_MSG_TEMP.T_ATTR_13
     *
     * @return the value of CX_O_MSG_TEMP.T_ATTR_13
     *
     * @mbggenerated
     */
    public Date gettAttr13() {
        return tAttr13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CX_O_MSG_TEMP.T_ATTR_13
     *
     * @param tAttr13 the value for CX_O_MSG_TEMP.T_ATTR_13
     *
     * @mbggenerated
     */
    public void settAttr13(Date tAttr13) {
        this.tAttr13 = tAttr13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CX_O_MSG_TEMP.T_ATTR_14
     *
     * @return the value of CX_O_MSG_TEMP.T_ATTR_14
     *
     * @mbggenerated
     */
    public Date gettAttr14() {
        return tAttr14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CX_O_MSG_TEMP.T_ATTR_14
     *
     * @param tAttr14 the value for CX_O_MSG_TEMP.T_ATTR_14
     *
     * @mbggenerated
     */
    public void settAttr14(Date tAttr14) {
        this.tAttr14 = tAttr14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CX_O_MSG_TEMP.DB_LAST_UPD_SRC
     *
     * @return the value of CX_O_MSG_TEMP.DB_LAST_UPD_SRC
     *
     * @mbggenerated
     */
    public String getDbLastUpdSrc() {
        return dbLastUpdSrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CX_O_MSG_TEMP.DB_LAST_UPD_SRC
     *
     * @param dbLastUpdSrc the value for CX_O_MSG_TEMP.DB_LAST_UPD_SRC
     *
     * @mbggenerated
     */
    public void setDbLastUpdSrc(String dbLastUpdSrc) {
        this.dbLastUpdSrc = dbLastUpdSrc == null ? null : dbLastUpdSrc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CX_O_MSG_TEMP.MSG_CONTEXT
     *
     * @return the value of CX_O_MSG_TEMP.MSG_CONTEXT
     *
     * @mbggenerated
     */
    public String getMsgContext() {
        return msgContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CX_O_MSG_TEMP.MSG_CONTEXT
     *
     * @param msgContext the value for CX_O_MSG_TEMP.MSG_CONTEXT
     *
     * @mbggenerated
     */
    public void setMsgContext(String msgContext) {
        this.msgContext = msgContext == null ? null : msgContext.trim();
    }



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CX_O_MSG_TEMP.T_ATTR_03
     *
     * @return the value of CX_O_MSG_TEMP.T_ATTR_03
     *
     * @mbggenerated
     */
    public String gettAttr03() {
        return tAttr03;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CX_O_MSG_TEMP.T_ATTR_03
     *
     * @param tAttr03 the value for CX_O_MSG_TEMP.T_ATTR_03
     *
     * @mbggenerated
     */
    public void settAttr03(String tAttr03) {
        this.tAttr03 = tAttr03 == null ? null : tAttr03.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CX_O_MSG_TEMP.T_ATTR_04
     *
     * @return the value of CX_O_MSG_TEMP.T_ATTR_04
     *
     * @mbggenerated
     */
    public String gettAttr04() {
        return tAttr04;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CX_O_MSG_TEMP.T_ATTR_04
     *
     * @param tAttr04 the value for CX_O_MSG_TEMP.T_ATTR_04
     *
     * @mbggenerated
     */
    public void settAttr04(String tAttr04) {
        this.tAttr04 = tAttr04 == null ? null : tAttr04.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CX_O_MSG_TEMP.T_ATTR_05
     *
     * @return the value of CX_O_MSG_TEMP.T_ATTR_05
     *
     * @mbggenerated
     */
    public String gettAttr05() {
        return tAttr05;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CX_O_MSG_TEMP.T_ATTR_05
     *
     * @param tAttr05 the value for CX_O_MSG_TEMP.T_ATTR_05
     *
     * @mbggenerated
     */
    public void settAttr05(String tAttr05) {
        this.tAttr05 = tAttr05 == null ? null : tAttr05.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CX_O_MSG_TEMP.T_ATTR_06
     *
     * @return the value of CX_O_MSG_TEMP.T_ATTR_06
     *
     * @mbggenerated
     */
    public String gettAttr06() {
        return tAttr06;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CX_O_MSG_TEMP.T_ATTR_06
     *
     * @param tAttr06 the value for CX_O_MSG_TEMP.T_ATTR_06
     *
     * @mbggenerated
     */
    public void settAttr06(String tAttr06) {
        this.tAttr06 = tAttr06 == null ? null : tAttr06.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CX_O_MSG_TEMP.T_ATTR_07
     *
     * @return the value of CX_O_MSG_TEMP.T_ATTR_07
     *
     * @mbggenerated
     */
    public String gettAttr07() {
        return tAttr07;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CX_O_MSG_TEMP.T_ATTR_07
     *
     * @param tAttr07 the value for CX_O_MSG_TEMP.T_ATTR_07
     *
     * @mbggenerated
     */
    public void settAttr07(String tAttr07) {
        this.tAttr07 = tAttr07 == null ? null : tAttr07.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CX_O_MSG_TEMP.T_ATTR_08
     *
     * @return the value of CX_O_MSG_TEMP.T_ATTR_08
     *
     * @mbggenerated
     */
    public String gettAttr08() {
        return tAttr08;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CX_O_MSG_TEMP.T_ATTR_08
     *
     * @param tAttr08 the value for CX_O_MSG_TEMP.T_ATTR_08
     *
     * @mbggenerated
     */
    public void settAttr08(String tAttr08) {
        this.tAttr08 = tAttr08 == null ? null : tAttr08.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CX_O_MSG_TEMP.T_ATTR_15
     *
     * @return the value of CX_O_MSG_TEMP.T_ATTR_15
     *
     * @mbggenerated
     */
    public String gettAttr15() {
        return tAttr15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CX_O_MSG_TEMP.T_ATTR_15
     *
     * @param tAttr15 the value for CX_O_MSG_TEMP.T_ATTR_15
     *
     * @mbggenerated
     */
    public void settAttr15(String tAttr15) {
        this.tAttr15 = tAttr15 == null ? null : tAttr15.trim();
    }

	public String getMsgType() {
		return msgType;
	}

	public void setMsgType(String msgType) {
		this.msgType = msgType;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}
}